### ISSUE TITLE
zombie walk

### ISSUE THREAD

**Issue by Creeperface01** [zzm317/MyZombie#13]
sometimes zombie walk into blocks when walking to player.

**Comment by zzm317** [comment]
Yep......But 2.9.0 fix a lot

**Comment by Creeperface01** [comment]
Ok And Will you release it?

**Comment by zzm317** [comment]
Give me your email and i will send you one

**Comment by Creeperface01** [comment]
honzaxp01@gmail.com thx :)

**Comment by zzm317** [comment]
I won't release it to public, since some chinese not only use my code but also delete my names and the name of values and the author and even sell them...But i write "Copy the code is banned" in chinese in my github....

**Comment by Creeperface01** [comment]
Ok

**Comment by zzm317** [comment]
Please Change $p->attack($this->dif * 2); to $p->setHealth($p->getHealth() - $this->dif * 2); in myzombie2.9.0 on line about 760

**Comment by Creeperface01** [comment]
Why?  P->attack works well

**Comment by Creeperface01** [comment]
You only forgot new EntityDamageEvent()

**Comment by haruajsuru** [comment]
can you send me the new version of your plugin?  I would like to use it on my server.

My email is: tomato_141@yahoo.com

Thanks :)

**Comment by KarNom** [comment]
Can I have a new version of the plugin? I promise not to publish it.
My Mail: andrei201936@gmail.com
