### ISSUE TITLE
Access to the latest version

### ISSUE THREAD

**Issue by rmstdope** [zzm317/MyZombie#18]
I am interested in running the plugin on my PM server. However, it seems the code has not been updated in quite some time, but at the same time, it seems development is ongoing. Is there any way to get access to the latest source? Preferably by updating the github repository so that other people (including myself) can pitch in on development and bugfixes.

If not, would it at least be possible get hold of the latest version for private use?

**Comment by zzm317** [comment]
If you can make sure you only use it for private use, I can send it to you by email

**Comment by Pub4Game** [comment]
@zzm317 can I get this plugin to my clients hosting?

**Comment by zzm317** [comment]
@Pub4Game ==If you promise don't sell it
is http://24serv.pro/ your site?
does it have a english version?

**Comment by Pub4Game** [comment]
Yes, I'm working on it. Unfortunately no English version. Is it possible to publish it on the forum?

**Comment by Pub4Game** [comment]
I will not sell) Only used

**Comment by doducquang** [comment]
I'm using this plugin and really enjoy it ^^

**Comment by Pub4Game** [comment]
@zzm317 Please send me plugin to email pub4game@gmail.com

**Comment by rock2rap** [comment]
I'm only use in my server and Guarantee not for sell and share.
Please send me rock2rapz@gmail.com

**Comment by zzm317** [comment]
@Pub4Game you can publish it on the forum and you can also put it in your hosting.
=_=

**Comment by zzm317** [comment]
@rock2rap =_=someone have alread update the version
and for some reason,i can't send you the latest version.
so sorry for that.

**Comment by zzm317** [comment]
@rock2rap and this plugin need to be changed to fit PM1,6
so i have stop developing the one for 1.4

**Comment by rock2rap** [comment]
ok thanks

**Comment by zzm317** [comment]
@rock2rap and i have upload the newest version just now

**Comment by rock2rap** [comment]
Yes!! you r the best!!

**Comment by Pub4Game** [comment]
If this is forbidden I will not do it. I will use the plugin for my server) I Promise not to distribute it

**Comment by zzm317** [comment]
@Pub4Game The only rule you must obey: NEVER SELL IT

**Comment by zzm317** [comment]
@Pub4Game and do what you like 
_(:з」∠)_

**Comment by Pub4Game** [comment]
I promise not to distribute and sell your plugin

**Comment by rock2rap** [comment]
even this plugin set to public. i'm also confirm to not for sell and shared

**Comment by zzm317** [comment]
@Pub4Game  @rock2rap ==you can publish it to anywhere now.

**Comment by Pub4Game** [comment]
I know it

**Comment by Pub4Game** [comment]
You send me the plugin? :((

**Comment by zzm317** [comment]
@Pub4Game I have update the plugin just now..Don't you see it?

**Comment by Pub4Game** [comment]
lol, Thanks
