### ISSUE TITLE
幾個問題

### ISSUE THREAD

**Issue by PEMapModder** [zzm317/MyZombie#5]
1. PM ~~不鼓勵~~ 禁止插件使用 CallbackTask
2. 減少 functions 的使用可達至較佳表現。

**Comment by kevin200** [comment]
作者好像不在这更新了

**Comment by PEMapModder** [comment]
I know

**Comment by zzm317** [comment]
只是不免费更新了而已

**Comment by zzm317** [comment]
以及。。其实我目前只会callbacktask。。其他没用过

**Comment by PEMapModder** [comment]
You must use PluginTask for plugin scheduled tasks. This is a standard such that PocketMine can cancel your tasks when the plugin is disabled.

**Comment by zzm317** [comment]
wow But I am so lazy that i don't want to change that...
It's still working, that's enough . Isn't it right?

**Comment by PEMapModder** [comment]
But your plugin doesn't get disabled completely when it gets disabled. And it doesn't work well with /reload since some of the old things didn't get garbaged.
